services:
  ui:
    container_name: poker-ui
    ports:
      - 4200:80
    build:
      context: src/ui
      dockerfile: Dockerfile
  api:
    container_name: poker-api
    ports:
      - 3000:3000
    build:
      context: src/api
      dockerfile: Dockerfile
    env_file:
      - src/api/docker.env
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gtop
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
