version: "3.9"
services:
  client-ui:
    ports:
      - 19500:80
    image: georgespanos/gtop-ui:stable
    deploy:
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 3
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: stop-first

  admin-ui:
    ports:
      - 19600:80
    image: georgespanos/gtop-admin-ui:stable
    deploy:
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 3
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: stop-first

  web-api:
    ports:
      - 19300:3000
    image: georgespanos/gtop-api:stable
    configs:
      - source: ppo-api.env
        target: /src/.env
    deploy:
      replicas: 2
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 3
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: stop-first

  calc-odds-api:
    image: georgespanos/gtop-calc-odds:stable
    ports:
      - 19400:7071
    depends_on:
      - db
    deploy:
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 3
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: stop-first
configs:
  ppo-api.env:
    external: true
      