version: '3.9'
services:
  client-ui:
    ports:
      - 4200:80
    build:
      context: src/ui
      dockerfile: Dockerfile
      secrets:
        - npmrc
      args:
        - TARGET=dev
    depends_on:
      - web-api
  migrate:
    build:
      context: src/web-api
      target: build
      secrets:
        - npmrc
    command: ['npx', 'prisma', 'migrate', 'deploy']
    env_file:
      - src/web-api/.env.docker
    depends_on:
      db:
        condition: service_healthy
  web-api:
    ports:
      - 3000:3000
    build:
      context: src/web-api
      secrets:
        - npmrc
    env_file:
      - src/web-api/.env.docker
    depends_on:
      migrate:
        condition: service_completed_successfully
      calc-odds-api:
        condition: service_started
  calc-odds-api:
    build:
      context: src/calc-odds-api
      secrets:
        - npmrc
    environment:
      - ITERATIONS=50000
    ports:
      - 7071:7071
    depends_on:
      - db
  db:
    container_name: playpokerodds-db
    image: postgres:15.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gtop
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', 'gtop', '-U', 'root']
      start_period: 10s
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    external: true
secrets:
  npmrc:
    file: .npmrc
