version: '3.9'
services:
  client-ui:
    ports:
      - 9500:80
    image: ${REPOSITORY_NAME}/ppo-ui:${TAG}
    deploy:
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: start-first

  admin-ui:
    ports:
      - 9600:80
    image: ${REPOSITORY_NAME}/ppo-admin-ui:${TAG}
    deploy:
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: start-first

  web-api:
    ports:
      - 9300:3000
    image: ${REPOSITORY_NAME}/ppo-api:${TAG}
    configs:
      - source: ppoapi-v4.conf
        target: /src/.env
    deploy:
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: start-first

  calc-odds-api:
    image: ${REPOSITORY_NAME}/ppo-calc-odds:${TAG}
    ports:
      - 9400:7071
    configs:
      - source: ppocalc-v4.conf
        target: /src/.env
    deploy:
      resources:
        limits:
          cpus: '1.00' # Maximum and minimum of 1 CPU
        reservations:
          cpus: '1.00' # Reserve 1 CPU to ensure it's always allocated
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: start-first
configs:
  ppoapi-v5.conf:
    external: true
  ppocalc-v4.conf:
    external: true
