services:
  client-ui:
    container_name: client-ui
    ports:
      - 4200:80
    build:
      context: src/ui
      dockerfile: Dockerfile
      args:
        - TARGET=dev
    depends_on:
      - web-api
  admin-ui:
    container_name: admin-ui
    ports:
      - 4300:80
    build:
      context: src/ui
      dockerfile: admin.Dockerfile
      args:
        - TARGET=dev
    depends_on:
      - web-api

  web-api:
    container_name: web-api
    ports:
      - 3000:3000
    build:
      context: src/web-api
    env_file:
      - src/web-api/docker.env
    depends_on:
      - db
      - calc-odds-api
  calc-odds-api:
    container_name: calc-odds-api
    build:
      context: src/calc-odds-api
    ports:
      - 7071:7071
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gtop
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
