version: "3.9"
services:
  client-ui:
    ports:
      - 9500:80
    image: georgespanos/gtop-ui:${TAG}
    deploy:
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 3
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: stop-first

  admin-ui:
    ports:
      - 9600:80
    image: georgespanos/gtop-admin-ui:${TAG}
    deploy:
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 3
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: stop-first

  web-api:
    ports:
      - 9300:3000
    image: georgespanos/gtop-api:${TAG}
    configs:
      - source: ppoapi.conf-v2
        target: /src/.env
    deploy:
      replicas: 1
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 3
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: stop-first

  calc-odds-api:
    image: georgespanos/gtop-calc-odds:${TAG}
    ports:
      - 9400:7071
    configs:
      - source: ppocalc.conf
        target: /src/.env
    deploy:
      replicas: 1
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
        max_attempts: 3
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: stop-first
configs:
  ppoapi.conf-v2:
    external: true
  ppocalc.conf:
    external: true
