services:
  api:
    container_name: api
    ports:
      - 3000:3000
    build:
      dockerfile: Dockerfile
    env_file:
      - docker.env
    depends_on:
      db:
        condition: service_healthy
      calc-odds-api:
        condition: service_started
  calc-odds-api:
    build:
      context: ../calc-odds-api
    ports:
      - 7071:7071
  db:
    container_name: playpokerodds-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gtop
    healthcheck:
      test: ["CMD", "pg_isready","-d", "gtop","-U", "root"]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
