services:
  api:
    container_name: api
    ports:
      - 3000:3000
    build:
      dockerfile: Dockerfile
    env_file:
      - docker.env
  calc-odds-api:
    build:
      context: ../calc-odds-api
    ports:
      - 7071:7071
    depends_on:
      - db
  db:
    container_name: playpokerodds-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gtop
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
