# fly.toml app configuration file generated for web-api on 2023-12-31T19:56:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "web-api"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
[env]
LEADERBOARD_MIN_GAMES = "2"
[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
