# fly.toml app configuration file generated for ppo-ui on 2023-12-31T19:40:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ppo-ui"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
