apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minikube-ingress
  namespace: playpokerodds
spec:
  rules:
    - host: playpokerodds.local
      http:
        paths:
          - path: /api/calcOdds
            pathType: Exact
            backend:
              service:
                name: calc-odds
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: web-api-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-ui-service
                port:
                  number: 80

                  

