# fly.toml app configuration file generated for ppo-calc-odds on 2024-03-07T00:49:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ppo-calc-odds'
primary_region = 'ams'

[build]
dockerfile = 'Dockerfile'

[http_service]
internal_port = 7071
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[env]
ITERATIONS = "50000"

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/liveness"

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
