# fly.toml app configuration file generated for ppo-calc-odds on 2023-12-31T19:49:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ppo-calc-odds"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 7071
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
[[services.http_checks]]
grace_period = 10
interval = 30
timeout = 5
path = "/liveness"
[env]
ITERATIONS = "50000"
[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
