# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Azure
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test: 
    runs-on: 'ubuntu-latest'
    env:
      JWT_SECRET: SOMEJWTSECRET
    steps:
      - uses: actions/checkout@v2
      - name: Test api
        run: npm run docker:test
  build:
    runs-on: 'ubuntu-latest'
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Run migrations
        env: 
           DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: npx prisma migrate deploy 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://gtopregistry.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_a347be6341134707bfdc72de13011e4f }}
          password: ${{ secrets.AzureAppService_ContainerPassword_fc25210fa3024b5992ff32953efff949 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gtopregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a347be6341134707bfdc72de13011e4f }}/gtop-api:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gtop-api'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_0ea8da4e89da448fbf814b7b58c20ff6 }}
          images: 'gtopregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a347be6341134707bfdc72de13011e4f }}/gtop-api:${{ github.sha }}'
