services:
  api:
    container_name: api
    ports:
      - 3000:3000
    build:
      dockerfile: Dockerfile
    env_file:
      - docker.env
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gtop
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  calc-odds:
    image: calc-poker-odds
    ports:
    - '7071:7071'