services:
  api:
    container_name: api
    ports:
      - 3000:3000
    build:
      dockerfile: Dockerfile
    command: npm test
    env_file:
      - docker.env
    depends_on:
      - db
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gtop
    ports:
      - '5432:5432'
