export enum EventType {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_FETCHED_ROUND = 'USER_FETCHED_ROUND',
  USER_POSTED_ANSWER = 'USER_POSTED_ANSWER',
  USER_POSTED__EXISTING_ANSWER = 'USER_POSTED_EXISTING_ANSWER',
  UI_ERROR = 'UI_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
