# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Calc Odds Api - build latest

on:
  push:
    branches:
      - "main"
    paths:
      - 'src/calc-odds-api/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.REPOSITORY_NAME }}/ppo-calc-odds:latest
          context: ./src/calc-odds-api
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}