# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Client UI

on:
  push:
    branches:
      - main
    paths:
      - "src/ui/**"
      - "!src/ui/admin/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          username: georgespanos
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: georgespanos/gtop-ui:${{ github.sha }},georgespanos/gtop-ui:latest
          context: ./src/ui

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "gtop-ui"
          slot-name: "production"
          publish-profile: ${{ secrets.UI_PUBLISH_PROFILE }}
          images: docker.io/georgespanos/gtop-ui:latest
