# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Test stack deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Deploy to VPS
        uses: kitconcept/docker-stack-deploy@v1.0.1
        with:
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_private_key: ${{ secrets.KEY }}
          registry: "docker.io"
          deploy_timeout: 120
          username: georgespanos
          password: ${{ secrets.CONTAINER_PASSWORD }}
          stack_file: "docker-stack.yml"
          stack_name: "mockstack"

