# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Web Api - build and deploy stable
on:
  push:
    tags:
      - "v*"
    paths:
      - "src/web-api/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    env:
      JWT_SECRET: SOMEJWTSECRET
    steps:
      - uses: actions/checkout@v3
      - name: Test api
        working-directory: ./src/web-api
        run: npm run docker:test
  build:
    runs-on: "ubuntu-latest"
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Run migrations
        working-directory: ./src/web-api
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: npx prisma migrate deploy

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          username: georgespanos
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: georgespanos/gtop-api:${{ github.ref_name }},georgespanos/gtop-api:stable
          context: ./src/web-api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        env:
          TAG: ${{ github.ref_name }}
          CONTAINER_USERNAME: ${{ secrets.CONTAINER_USERNAME }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: TAG,CONTAINER_USERNAME
          script: docker service update api-poker-odds --image=$CONTAINER_USERNAME/gtop-api:$TAG
