# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, Test and Deploy Web Api
on:
  push:
    branches:
      - main
    paths:
      - "src/web-api/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    env:
      JWT_SECRET: SOMEJWTSECRET
    steps:
      - uses: actions/checkout@v3
      - name: Test api
        working-directory: ./src/web-api
        run: npm run docker:test
  build:
    runs-on: "ubuntu-latest"
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Run migrations
        working-directory: ./src/web-api
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: npx prisma migrate deploy

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://gtopregistry.azurecr.io/
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: gtopregistry.azurecr.io/${{ secrets.CONTAINER_USERNAME }}/gtop-api:${{ github.sha }}
          context: ./src/web-api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "gtop-api"
          slot-name: "production"
          publish-profile: ${{ secrets.API_PUBLISH_PROFILE }}
          images: "gtopregistry.azurecr.io/${{ secrets.CONTAINER_USERNAME }}/gtop-api:${{ github.sha }}"
